# Generated by Django 2.2.12 on 2020-04-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articles',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
