# Generated by Django 2.2.12 on 2020-04-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20200416_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='blocked_articles',
            field=models.TextField(default=''),
        ),
    ]
